// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;
using VTSClient.iOS.DataSources;

namespace VTSClient.iOS
{
	public partial class MenuTableViewController : UITableViewController
	{
		public MenuTableViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			var clockVC = Storyboard.InstantiateViewController("VacationsTableViewController");
			ShowDetailViewController(clockVC, this);
		}


		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			var sections = new string[] { "All", "Opened", "Closed" };
			TableView.Source = new MenuTableViewSource(this, sections);
		}
	}
}
