// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace VTSClient.iOS
{
	public partial class AddOrUpdateViewController : UIViewController
	{
		public AddOrUpdateViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
