// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace VTSClient.iOS
{
	public partial class VacationViewController : UITableViewController
	{
		public VacationViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
